services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
      - FETCH_TIMEOUT=60000
    env_file:
      - .env 
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
