name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker (optional, can skip if not needed)
      
      - name: Build Docker image with docker compose
        run: |
          docker compose -f docker-compose.yml build  # Build the image with docker compose
          
      - name: Run tests (optional)
        run: |
          docker compose -f docker-compose.yml run --rm yourapp_test  # Run tests in the container (if needed)

  deploy:
    runs-on: ubuntu-latest  # Run the deploy job on the same Ubuntu runner

    needs: build-and-test  # Ensure this job runs after the build-and-test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.5  # Use SSH to connect to your VPS
        with:
          host: ${{ secrets.HOSTINGER_SERVER_IP }}  # VPS IP address
          username: ${{ secrets.HOSTINGER_SSH_USER }}  # SSH username (e.g., 'root')
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}  # SSH private key
          port: 22
          script: |
            cd /Media-Nexus  # Navigate to your app directory (if needed)
            git pull origin main  # Ensure your server has the latest code
            docker compose -f docker-compose.yml up --build -d  # Build and start the containers in detached mode
